### ISSUE TITLE
更新检查速度比较慢

### ISSUE THREAD

**Issue by mjason** [LISTENAI/lisa#1]
```js
"warn-if-update-available": {
      "timeoutInDays": 7,
      "registry": "https://registry.npm.taobao.org",
      "message": "lisa 可从 <%= chalk.greenBright(config.version) %> 更新到 <%= chalk.greenBright(latest) %> ，请输入命令 lisa update 进行更新。"
    }
```

```
lisa:@oclif/plugin-warn-if-update-available:hooks:init start /Users/mj/dev/lisa/lisa/node_modules/@oclif/plugin-warn-if-update-available/lib/hooks/init/check-update +0ms
  lisa:@listenai/lisa:hooks:init done +262ms
  lisa:@listenai/lisa:hooks:init done +0ms
  lisa:@oclif/plugin-warn-if-update-available:hooks:init done +257ms
  lisa:@listenai/lisa:hooks:init done +334ms
```

如果选择中文或者国外的速度都比较慢，且通过npm来做版本确定，速度上比较慢，后续考虑还其他方式来解决

**Comment by monsterboom** [comment]
> ```js
> "warn-if-update-available": {
>       "timeoutInDays": 7,
>       "registry": "https://registry.npm.taobao.org",
>       "message": "lisa 可从 <%= chalk.greenBright(config.version) %> 更新到 <%= chalk.greenBright(latest) %> ，请输入命令 lisa update 进行更新。"
>     }
> ```
> 
> ```
> lisa:@oclif/plugin-warn-if-update-available:hooks:init start /Users/mj/dev/lisa/lisa/node_modules/@oclif/plugin-warn-if-update-available/lib/hooks/init/check-update +0ms
>   lisa:@listenai/lisa:hooks:init done +262ms
>   lisa:@listenai/lisa:hooks:init done +0ms
>   lisa:@oclif/plugin-warn-if-update-available:hooks:init done +257ms
>   lisa:@listenai/lisa:hooks:init done +334ms
> ```
> 
> 如果选择中文或者国外的速度都比较慢，且通过npm来做版本确定，速度上比较慢，后续考虑还其他方式来解决

没细看该plugin底层逻辑，不过可以不使用该plugin，自己实现个勾子。
直接使用 npm view dist-tags查询latest版本在本地缓存，每天更新查询一次。
对比当前version，进行提示。

**Comment by monsterboom** [comment]
没细看该plugin底层逻辑，不过可以不使用该plugin，自己实现个勾子。
直接使用 npm view dist-tags查询latest版本在本地缓存，每天更新查询一次。
对比当前version，进行提示。

**Comment by monsterboom** [comment]
#4
